export const EVENT_CREATING = "EVENT_CREATING";
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS";
export const EVENT_CREATE_ERROR = "EVENT_CREATE_ERROR";
export const EVENT_REQUESTING = "EVENT_REQUESTING";
export const EVENT_REQUEST_SUCCESS = "EVENT_REQUEST_SUCCESS";
export const EVENT_REQUEST_ERROR = "EVENT_REQUEST_ERROR";
