export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_EXISTING = 'LOGIN_EXISTING';
export const SET_CURRENT_LOGGED_USER = 'SET_CURRENT_LOGGED_USER';
export const LOGOUT = 'LOGOUT';