export const MOVE_ITEM_REQUEST = "MOVE_ITEM_REQUEST";
export const MOVE_ITEM_SUCCESS = "MOVE_ITEM_SUCCESS";
export const MOVE_ITEM_ERROR = "MOVE_ITEM_ERROR";
export const INITIALIZE_LIST = "INITIALIZE_LIST";
